### ISSUE TITLE
undefined method

### ISSUE THREAD

**Issue by dikaio** [andrusha/middleman-cloudfront#17]
I've been running across this error since upgrading to cloud front  0.1.1, was hoping someone might have insight into the error. Thanks!

``
middleman-cloudfront/commands.rb:70:in `invalidate': undefined method `invalidations' for nil:NilClass (NoMethodError)
``

**Comment by andrusha** [comment]
@dikaio are you sure you've specified correct `distribution_id` and you have enough rights on it? We should put some meaningful error message here, but that's likely the source of the problem.

**Comment by dikaio** [comment]
Hi @andrusha. It is possible that I have set the cloud front distribution incorrectly. My config has:

``ruby
activate :cloudfront do |cf|
  cf.access_key_id                = ENV['AWS_ACCESS_KEY_ID']
  cf.secret_access_key         = ENV['AWS_SECRET_ACCESS_KEY']
  cf.distribution_id                 =  'd13v31z5c5era1'
  # cf.filter = /\.html$/i  # default is /.*/
  # cf.after_build = true
end
``
As for the permissions I've tried both with an IAM user with a policy as defined in the README and also with my root credentials. Both flopped :).

It is accessing AWS I believe this is the complete message I get.

``
## Invalidating files on CloudFront
Invalidating 9 files. It might take 10 to 15 minutes until all files are invalidated.
Please check the AWS Management Console to see the status of the invalidation.
/Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/middleman-cloudfront-0.1.1/lib/middleman-cloudfront/commands.rb:70:in `invalidate': undefined method `invalidations' for nil:NilClass (NoMethodError)
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.7/lib/middleman-core/cli.rb:72:in `method_missing'
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.7/lib/middleman-core/cli.rb:20:in `start'
	from /Users/dad/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/middleman-core-3.3.7/bin/middleman:18:in `<top (required)>'
	from /Users/dad/.rbenv/versions/2.1.5/bin/middleman:23:in `load'
	from /Users/dad/.rbenv/versions/2.1.5/bin/middleman:23:in `<main>'
``

**Comment by manuelmeurer** [comment]
It's definitely either a typo in your distribution ID or invalid permissions. And it's impossible to debug from the outside.
