### ISSUE TITLE
Middleman v4.0 support

### ISSUE THREAD

**Issue by bb-generation** [andrusha/middleman-cloudfront#18]
Middleman is currently on its way to release verison 4.0. Unfortunately, middleman-cloudfront still has a dependency which restricts versions > 3.

You can find recent middleman alpha releases here: https://rubygems.org/gems/middleman-core (4.0.0.alpha.6 is the most recent one as of this writing)

I would really appreciate it, if this very helpful gem would introduce support for version 4.0

**Comment by manuelmeurer** [comment]
Unfortunately I won't have time to work on it. If you, or someone else, could do the first step and find out what changed in Middleman 4.0 and needs to be fixed for middleman-cloudfront to work, that would be very helpful!

**Comment by rosskevin** [comment]
@manuelmeurer I've done the conversion to middleman 4 - tests pass - though I have not yet used it in my app (which I will do over the next couple of days).

https://github.com/rosskevin/middleman-cloudfront/tree/middleman-4

The code is different enough that I could recommend you create a `v3-maintenance` branch before merging my PR.  Once I feel good about it, I'll submit, but wanted to save anyone else the time before they also converted it.

**Comment by rosskevin** [comment]
PR is good to merge and release as a 4.x only compatible version
