### ISSUE TITLE
RubyGems dependencies not correct

### ISSUE THREAD

**Issue by balthisar** [andrusha/middleman-cloudfront#27]
Despite the correct gemspec for 0.2.1 here on Github, the 0.2.1 on rubygems.org is still stuck at `middleman-core ~> 3.0` for some reason. I'm not sure how that might have happened, as you commit history seems to indicate you update the dependency before bumping the version!

In any case, it's breaking Bundler for automatic installs. You might want to bump the version and release it again.

I'll do a local install from this repo for the time being.

**Comment by manuelmeurer** [comment]
Actually we are looking to support Middleman v3 and v4 with the next release (which should be v1.0).
https://github.com/andrusha/middleman-cloudfront/issues/26
The dependency on Middleman v3.x for middleman-cloudfront v0.2.1 is correct.
You can use master for Middleman v4 at your own risk for now. 😄
