### ISSUE TITLE
gem old dependency

### ISSUE THREAD

**Issue by RealSilo** [andrusha/middleman-cloudfront#28]
Hey @andrusha ! Thanks for the gem! First time using it and looks awesome, although I ran into this issue. Could you pls update the dependencies? Thanks a lot!    

    Bundler could not find compatible versions for gem "middleman-core":

      In snapshot (Gemfile.lock):
      
        middleman-core (= 4.1.9)

      In Gemfile:

        middleman (>= 4.0.0) was resolved to 4.1.9, which depends on
          middleman-core (= 4.1.9)

        middleman-cloudfront (~> 0.2.1) was resolved to 0.2.1, which depends on
          middleman-core (~> 3.0)

        .......

**Comment by manuelmeurer** [comment]
Unfortunately this gem is not compatible with Middleman 4 yet, see #26.
